---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rodrigonascimento
  name: project2-pv-rodrigonascimento
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rodrigonascimento-playlist-recommender
  template:
    metadata:
      labels:
        app: rodrigonascimento-playlist-recommender
    spec:
      containers:
      - name: ml-container
        image: docker.io/rodrigosalesn/ml-container:1.0
        imagePullPolicy: Always
        env:
        - name: URL_VAR
          value: "https://raw.githubusercontent.com/rodrigo-salesn/project02/master/2023_spotify_ds2.csv"
        volumeMounts:
        - name: shared-storage
          mountPath: shared
      - name: front-container
        image: docker.io/rodrigosalesn/front-container:1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: shared-storage
          mountPath: shared
        ports:
        - containerPort: 32213
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: project2-pv-rodrigonascimento
